# Arch Linux system packages
# Package names specific to Arch/AUR
# Package configs and features inherit from settings.toml unless overridden here

[project.settings.system.packages]
packages = [
    "git",
    "vim",
    "neovim",
    "htop",
    "zsh",
    "tmux",
    "base-devel",  # Arch-specific: development tools
    "yay",         # AUR helper (if using AUR)
    # Zsh plugins
    "zsh-syntax-highlighting",
    "zsh-autosuggestions",
    "zsh-history-substring-search",
    # Fuzzy finder
    "fzf",
    # Better CLI tools
    "exa",   # Modern replacement for ls
    "bat",   # Cat with syntax highlighting
    "wlogout",  # Logout menu for Hyprland
]

# Arch-specific zsh plugin paths
[project.settings.system.packages.config.zsh.plugin_paths]
syntax_highlighting = "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
autosuggestions = "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
history_substring_search = "/usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
fzf_key_bindings = "/usr/share/fzf/key-bindings.zsh"
fzf_completion = "/usr/share/fzf/completion.zsh"

# Override default package configs or features here if needed for Arch
# Example: Override features for Arch
# [project.settings.system.packages.features]
# python = { version = "3.13.0" }  # Arch-specific Python version
# go = { version = "1.21.0" }  # Add Go for Arch

