"""Enumerations for colorscheme generator configuration."""

from enum import Enum


class Backend(str, Enum):
    """Supported color scheme backends.

    Each backend extracts colors from images using different methods:
    - PYWAL: Uses pywal (Python/CLI) for color extraction
    - WALLUST: Uses wallust (Rust binary) for color extraction
    - CUSTOM: Uses custom Python implementation with PIL
    """

    PYWAL = "pywal"
    WALLUST = "wallust"
    CUSTOM = "custom"


class ColorFormat(str, Enum):
    """Output file formats for color schemes.

    These formats are generated by OutputManager using Jinja2 templates.
    """

    JSON = "json"
    SHELL = "sh"
    CSS = "css"
    GTK_CSS = "gtk.css"  # GTK CSS with @define-color syntax
    YAML = "yaml"
    TOML = "toml"
    SEQUENCES = "sequences"  # Terminal color sequences for dynamic updates


class ColorAlgorithm(str, Enum):
    """Color extraction algorithms for custom backend.

    These algorithms are used by the custom backend to extract
    dominant colors from images using PIL/Pillow.
    """

    KMEANS = "kmeans"
    MEDIAN_CUT = "median_cut"
    OCTREE = "octree"
