# Output configuration (controlled by OutputManager, not backends)
[output]
directory = "$HOME/.cache/colorscheme"
formats = ["json", "sh", "css", "yaml"]

# Generation defaults
[generation]
default_backend = "pywal"
default_color_count = 16
saturation_adjustment = 1.0

# Backend-specific settings (for color extraction only)
[backends.pywal]
# Pywal writes to ~/.cache/wal/ internally (we just read from there)
cache_dir = "$HOME/.cache/wal"
use_library = false  # Use pywal CLI (library mode has API issues)

[backends.wallust]
# Wallust outputs JSON to stdout (we parse it)
output_format = "json"
backend_type = "resized"

[backends.custom]
# Custom backend extracts colors using PIL
algorithm = "kmeans"
n_clusters = 16

# Template configuration (for OutputManager)
[templates]
directory = "templates"
strict_mode = true

