"""Configuration file management."""

from pathlib import Path

from hyprpaper_manager.config.config import HyprpaperConfig


class ConfigManager:
    """Manage hyprpaper configuration file."""

    def __init__(self, config: HyprpaperConfig):
        """Initialize config manager.

        Args:
            config: Hyprpaper configuration
        """
        self.config = config

    def ensure_config_exists(self) -> bool:
        """Ensure config file exists, create if needed.

        Returns:
            True if config was created, False if already existed

        Raises:
            OSError: If config file cannot be created
        """
        if self.config.config_file.exists():
            return False

        if not self.config.auto_create_config:
            return False

        # Create config directory if needed
        self.config.config_file.parent.mkdir(parents=True, exist_ok=True)

        # Generate and write config
        config_content = self._generate_config()
        self.config.config_file.write_text(config_content)

        return True

    def _generate_config(self) -> str:
        """Generate hyprpaper config file content.

        Returns:
            Config file content as string
        """
        lines = [
            "# Hyprpaper configuration",
            "# Generated by hyprpaper-manager",
            "",
        ]

        # IPC setting
        if self.config.ipc_enabled:
            lines.extend(
                [
                    "# Enable IPC for runtime control",
                    "ipc = on",
                    "",
                ]
            )

        # Splash settings
        if self.config.splash_enabled:
            lines.extend(
                [
                    "# Splash screen settings",
                    "splash = true",
                    f"splash_offset = {self.config.splash_offset}",
                    f"splash_color = {self.config.splash_color}",
                    "",
                ]
            )

        # Add note about wallpaper management
        lines.extend(
            [
                "# Wallpapers are managed via hyprpaper-manager",
                "# Use 'hyprpaper-manager set <wallpaper>' to set wallpapers",
                "# Use 'hyprpaper-manager random' for random wallpapers",
                "",
            ]
        )

        return "\n".join(lines)

    def validate_config(self) -> tuple[bool, str]:
        """Validate config file exists and is readable.

        Returns:
            Tuple of (is_valid, error_message)
        """
        if not self.config.config_file.exists():
            return (
                False,
                f"Config file not found: {self.config.config_file}",
            )

        if not self.config.config_file.is_file():
            return (
                False,
                f"Config path is not a file: {self.config.config_file}",
            )

        try:
            self.config.config_file.read_text()
            return (True, "")
        except Exception as e:
            return (False, f"Cannot read config file: {e}")
